from datetime import datetime

START_YEAR = 2025
START_MONTH = 6
START_DAY = 24
START_HOUR = 13
START_MINUTE = 50

END_YEAR = START_YEAR
END_MONTH = START_MONTH
END_DAY = START_DAY
END_HOUR = 16
END_MINUTE = 20
START_TIME = datetime(START_YEAR, START_MONTH, START_DAY, START_HOUR, START_MINUTE, 00)
END_TIME = datetime(END_YEAR, END_MONTH, END_DAY, END_HOUR, END_MINUTE)
