# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feeder.proto
# Protobuf Python Version: 6.33.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    3,
    '',
    'feeder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66\x65\x65\x64\x65r.proto\x12\x03sd3\"R\n\rBusConnection\x12\x0e\n\x06\x62us_id\x18\x01 \x01(\r\x12\x0f\n\x07phase_a\x18\x02 \x01(\x08\x12\x0f\n\x07phase_b\x18\x03 \x01(\x08\x12\x0f\n\x07phase_c\x18\x04 \x01(\x08\"\xe1\x05\n\x06\x46\x65\x65\x64\x65r\x12\x15\n\rsource_bus_id\x18\x01 \x01(\r\x12\x1f\n\x05lines\x18\x02 \x03(\x0b\x32\x10.sd3.Feeder.Line\x12\x1f\n\x05loads\x18\x03 \x03(\x0b\x32\x10.sd3.Feeder.Load\x12)\n\ncapacitors\x18\x04 \x03(\x0b\x32\x15.sd3.Feeder.Capacitor\x12)\n\nregulators\x18\x05 \x03(\x0b\x32\x15.sd3.Feeder.Regulator\x12-\n\x0ctransformers\x18\x06 \x03(\x0b\x32\x17.sd3.Feeder.Transformer\x12\x1e\n\x05\x62uses\x18\x07 \x03(\x0b\x32\x0f.sd3.Feeder.Bus\x1a\'\n\x03\x42us\x12\n\n\x02id\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\r\x12\t\n\x01y\x18\x03 \x01(\r\x1a\x94\x01\n\x04Line\x12\n\n\x02id\x18\x01 \x01(\r\x12$\n\x08\x66rom_bus\x18\x02 \x01(\x0b\x32\x12.sd3.BusConnection\x12\"\n\x06to_bus\x18\x03 \x01(\x0b\x32\x12.sd3.BusConnection\x12\x15\n\rlength_meters\x18\x04 \x01(\r\x12\x0e\n\x06switch\x18\x05 \x01(\x08\x12\x0f\n\x07\x65nabled\x18\x06 \x01(\x08\x1a\x33\n\x04Load\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1f\n\x03\x62us\x18\x02 \x01(\x0b\x32\x12.sd3.BusConnection\x1a\x38\n\tCapacitor\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1f\n\x03\x62us\x18\x02 \x01(\x0b\x32\x12.sd3.BusConnection\x1a\x62\n\tRegulator\x12\n\n\x02id\x18\x01 \x01(\r\x12\x16\n\x0etransformer_id\x18\x02 \x01(\r\x12\x0f\n\x07phase_a\x18\x03 \x01(\x08\x12\x0f\n\x07phase_b\x18\x04 \x01(\x08\x12\x0f\n\x07phase_c\x18\x05 \x01(\x08\x1a\x46\n\x0bTransformer\x12\n\n\x02id\x18\x01 \x01(\r\x12+\n\x0f\x62us_connections\x18\x02 \x03(\x0b\x32\x12.sd3.BusConnectionb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feeder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUSCONNECTION']._serialized_start=21
  _globals['_BUSCONNECTION']._serialized_end=103
  _globals['_FEEDER']._serialized_start=106
  _globals['_FEEDER']._serialized_end=843
  _globals['_FEEDER_BUS']._serialized_start=370
  _globals['_FEEDER_BUS']._serialized_end=409
  _globals['_FEEDER_LINE']._serialized_start=412
  _globals['_FEEDER_LINE']._serialized_end=560
  _globals['_FEEDER_LOAD']._serialized_start=562
  _globals['_FEEDER_LOAD']._serialized_end=613
  _globals['_FEEDER_CAPACITOR']._serialized_start=615
  _globals['_FEEDER_CAPACITOR']._serialized_end=671
  _globals['_FEEDER_REGULATOR']._serialized_start=673
  _globals['_FEEDER_REGULATOR']._serialized_end=771
  _globals['_FEEDER_TRANSFORMER']._serialized_start=773
  _globals['_FEEDER_TRANSFORMER']._serialized_end=843
# @@protoc_insertion_point(module_scope)
